export default {
    Requests: {
        FETCH_ACTIVE_LANGUAGE: "FETCH_ACTIVE_LANGUAGE",
        SET_WEB3_TO_STORE: "SET_WEB3_TO_STORE",
        FETCH_SMARTCONTRACTS: "FETCH_SMARTCONTRACTS",
        GENERATE_SMARTCONTRACT_OBJECT: "GENERATE_SMARTCONTRACT_OBJECT"

    },
    Success: {
        GENERATED_SMARTCONTRACT_OBJECT: "GENERATED_SMARTCONTRACT_OBJECT",
        RECEIVED_SMARTCONTRACTS: "RECEIVED_SMARTCONTRACTS",

    },
    Failure: {

    },
}